#!/bin/bash
if [[ $RUN_SCRIPT != '' ]]
then
	echo 'Using Custom-injected Run Script'
	source $RUN_SCRIPT
else
	echo 'Using Prepared Run Script'
	echo "Current STEAM_COMPAT_DATA_PATH=$STEAM_COMPAT_DATA_PATH ; Default: /proton-prefix"
	echo "Current STEAM_COMPAT_CLIENT_INSTALL_PATH=$STEAM_COMPAT_CLIENT_INSTALL_PATH ; Default: /root/.steam"
	proton runinprefix $APP_MOUNT/$EXECUTABLE_PATH
fi