---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enshrouded-dedicated-server
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: enshrouded
        image: quay.io/steamutils/proton-runner:latest
        env:
        - name: STEAMCMD_ARGS
          value: '+@sSteamCmdForcePlatformType windows +force_install_dir /steamapp +login anonymous +app_update 2278520 -public validate +quit'
        args: ["enshrouded_server.exe"]
        volumeMounts:
        - mountPath: /steamapp
          name: steamapp
        - mountPath: /steamapp/enshrouded_server.json
          name: config
        ports:
        - name: query-udp
          containerPort: 15637
          hostPort: 15637
          protocol: UDP
      volumes:
      - name: steamapp
        persistentVolumeClaim:
          claimName: steamapp-2278520
      - name: config
        hostPath:
          path: ./enshrouded_server.json
          type: File
